<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectYear_DropDownSelectValue(above1930)</name>
   <tag></tag>
   <elementGuidId>b37a5915-70e5-4c5a-bfb7-3194af71ebc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[text()=&quot;1930&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
