<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>continueBtn</name>
   <tag></tag>
   <elementGuidId>a7ba331d-c12c-4c57-8013-1250462c0c27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mcf__btn.-icon-left.ng-tns-c184-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7510764b-caff-4e1f-8507-73f206b74ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1bf9df09-5112-4b6a-b07e-8d60f2daf5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mcf__btn -icon-left ng-tns-c184-1</value>
      <webElementGuid>f67d1f29-53a1-4772-8702-0a82f279fb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue </value>
      <webElementGuid>03381ed5-e403-423c-9c81-726667d3298b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/iam-root[1]/div[@class=&quot;iam-holder&quot;]/div[@class=&quot;page-body&quot;]/iam-login[@class=&quot;ng-tns-c184-1 ng-star-inserted&quot;]/div[@class=&quot;iam-body ng-tns-c184-1 prelogin-body ng-trigger ng-trigger-fadeIn&quot;]/div[@class=&quot;container-fluid ng-tns-c184-1&quot;]/div[@class=&quot;row ng-tns-c184-1 ng-trigger ng-trigger-fadeIn ng-star-inserted&quot;]/div[@class=&quot;col-xs-12 col-sm-6 col-md-6 login-wrapper prelogin ng-tns-c184-1&quot;]/div[@class=&quot;step-btns ng-tns-c184-1 ng-star-inserted&quot;]/button[@class=&quot;mcf__btn -icon-left ng-tns-c184-1&quot;]</value>
      <webElementGuid>7345bbe6-33c1-475d-9dd8-94b15dbc5376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>487f343a-eae7-441e-91ea-2d9dbf713d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::button[1]</value>
      <webElementGuid>911fbf88-a105-419c-b4fb-17e05b648b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::button[1]</value>
      <webElementGuid>84d7468c-5976-40f7-8407-8a5d933fbdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release 3.0.0-RELEASE-Bug-Fixes-angular-12 DEV'])[1]/preceding::button[1]</value>
      <webElementGuid>bfa074cf-c45b-4a0c-b5de-48a6b1877c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>3717921d-c07b-4654-8eaf-3a6bc2b76484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>1875dbc6-eb49-4c60-91c2-7bb916543898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Continue ' or . = ' Continue ')]</value>
      <webElementGuid>472ba9bd-b293-47c3-8a40-77c5d06f9207</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
