<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>username</name>
   <tag></tag>
   <elementGuidId>4bef0d7a-6728-40b1-a0bd-b358f87fd73a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mcf__input.ng-untouched.ng-pristine.ng-invalid.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Please enter your username&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>842a4914-a113-414f-ba7b-20dd5ccdec28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mcf__input ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>63fadfde-2315-4b53-80c7-cf2d9a6fe8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9f5e768c-7a28-42b7-b3dd-ce342e87bc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>055ab96c-2bd9-4829-8e9d-f95158213701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9339458f-ab30-44cd-9479-99ae5b45dfba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b1ea26e1-bf72-4e02-95d2-c68e72cfe435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bbeef1a5-f62c-450b-97cc-93247dde849a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter your username</value>
      <webElementGuid>b5da5a4e-ef9d-405d-bbd9-3a827d6826e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validateonchange</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eed41194-6d2f-4cef-9c9b-fde444994c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>419fd70a-aa0a-4033-9f0d-14f2c14ee1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/iam-root[1]/div[@class=&quot;iam-holder&quot;]/div[@class=&quot;page-body&quot;]/iam-login[@class=&quot;ng-tns-c184-1 ng-star-inserted&quot;]/div[@class=&quot;iam-body ng-tns-c184-1 prelogin-body ng-trigger ng-trigger-fadeIn&quot;]/div[@class=&quot;container-fluid ng-tns-c184-1&quot;]/div[@class=&quot;row ng-tns-c184-1 ng-trigger ng-trigger-fadeIn ng-star-inserted&quot;]/div[@class=&quot;col-xs-12 col-sm-6 col-md-6 login-wrapper prelogin ng-tns-c184-1&quot;]/mcf-input[@class=&quot;ng-tns-c184-1 ng-star-inserted&quot;]/div[@class=&quot;mcf-input&quot;]/div[@class=&quot;mcf-input-wrapper ng-star-inserted&quot;]/input[@class=&quot;mcf__input ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]</value>
      <webElementGuid>90f593cf-47fa-4a89-980a-531f1e2fa5cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='']</value>
      <webElementGuid>b3f1a90e-0fbe-415d-8227-64ca9848acf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>edcea3d8-6059-4ee3-b6ad-3b82088c7581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Please enter your username' and @type = 'text']</value>
      <webElementGuid>1664e028-4061-476f-9295-a5fdb8ffc455</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
