<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>enterCustomerCode</name>
   <tag></tag>
   <elementGuidId>72673d0c-e9f7-4a67-b904-2e9969eabe96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cuscod']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cuscod</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Customer Code&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67a854b6-e6c6-4cd8-91ec-1a2eac6ae428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>882454a1-9574-4cb8-a17e-f1acf5791131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cuscod</value>
      <webElementGuid>a0a82874-972c-40d8-bfa8-7ee3f1df4fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cuscod</value>
      <webElementGuid>d4db2e27-f733-42cc-9fe8-0e78a8a5f862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>7568acbf-b6ae-4459-8d66-bcbc1335e5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter 'Customer Code'</value>
      <webElementGuid>8133f965-cbbc-4591-8f95-a7b793a748f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>6771a93f-0020-4145-928f-702f0cf3bcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upperCase</value>
      <webElementGuid>620424b5-f850-40c2-9777-7282e05aebf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cuscod&quot;)</value>
      <webElementGuid>afef22d8-4aca-49e0-94c9-fb563177ffef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cuscod']</value>
      <webElementGuid>cff4b4f7-e51c-42af-aeed-d0a3d377c8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custform_custFieldSet-fields']/div[3]/div[2]/div/input</value>
      <webElementGuid>1d54f92e-a911-4a5e-8ec0-b06192e0deb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c4c31ad2-6abe-4f98-970b-d65f1ac14626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cuscod' and @id = 'cuscod' and @title = concat(&quot;Enter &quot; , &quot;'&quot; , &quot;Customer Code&quot; , &quot;'&quot;)]</value>
      <webElementGuid>b7f0b34c-8a3f-4a8e-b8e1-b9f4cd49c878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
