<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>enterAddress1</name>
   <tag></tag>
   <elementGuidId>cc96371e-7ac0-405c-920d-d0f344e334f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='biladd001']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#biladd001</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Billing Address 1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>421df591-b7de-4da3-b25c-881c7d2fd1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36ab5af2-f82b-42ec-a5a7-eb6b0f1dc098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>biladd001</value>
      <webElementGuid>61cf1903-3210-413b-a8a6-bbbde8685a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>biladd001</value>
      <webElementGuid>d6ddb6e5-5fc9-40be-a205-d8af3b8f2af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>f2dd3bec-dafa-40da-a390-6a86acaa0a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter 'Billing Address 1'</value>
      <webElementGuid>0d1209c9-1bcf-4d20-90ee-80858e672b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>8f434962-2ec3-40f9-89d8-da9b65e2bf27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upperCase</value>
      <webElementGuid>fe695dd2-51d1-4924-bae7-fa584cdb0cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custform_custFieldSet-fields&quot;)/div[@class=&quot;col-12 col-lg-2 col-md-3 col-sm-3 col-xl-2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/input[@id=&quot;biladd001&quot;]</value>
      <webElementGuid>a719fd7f-25f4-4991-afb4-81c7f2785a4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='biladd001']</value>
      <webElementGuid>7ea21501-aaf7-43a1-a2e6-d8737fa13410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custform_custFieldSet-fields']/div[7]/div[2]/div/input</value>
      <webElementGuid>711006dc-32e8-4f92-a34b-bff31275db42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/input</value>
      <webElementGuid>97902fb9-ba38-450f-a9e7-4ec52980f5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'biladd001' and @id = 'biladd001' and @title = concat(&quot;Enter &quot; , &quot;'&quot; , &quot;Billing Address 1&quot; , &quot;'&quot;)]</value>
      <webElementGuid>ef14db50-c3a7-4df6-b1ac-00c3f19a6b56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
