<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>enterCurrencyCode</name>
   <tag></tag>
   <elementGuidId>239f838c-bffe-41d3-b377-bfb9cdcad99a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='curcodG_ref']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#curcodG_ref</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Currency Code&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47df5879-cc98-42ab-9700-764324df8c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>897d0021-cd80-488f-9a9c-07abcbacb66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>curcodG_ref</value>
      <webElementGuid>a9ff3432-15b9-405e-8efc-6001cb73ea78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>curcodG_ref</value>
      <webElementGuid>edc23477-20f9-4913-8f79-fcac9e2cec44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>360d5973-76d2-48cb-bc15-580f47e6bea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter 'Currency Code'</value>
      <webElementGuid>84e66874-192a-42e8-b838-073451c93a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7b11977f-5aae-4bb0-8c65-77311aa4e818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upperCase</value>
      <webElementGuid>dfe0cfcb-e881-4e7e-a16e-1e9eb9922d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;curcodG_ref&quot;)</value>
      <webElementGuid>d4841877-f50b-4640-9f66-deda475cf0ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='curcodG_ref']</value>
      <webElementGuid>4a21592c-5535-46bb-a084-14b79ad43b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='refForm_search']/div/div/div[2]/div/input</value>
      <webElementGuid>b7b7aba9-b3dc-4c8f-8dbc-34cc482e9bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/fieldset/div/div/div[2]/div/input</value>
      <webElementGuid>0a0d672c-ebcb-49d3-8715-72c321e91eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'curcodG_ref' and @id = 'curcodG_ref' and @title = concat(&quot;Enter &quot; , &quot;'&quot; , &quot;Currency Code&quot; , &quot;'&quot;)]</value>
      <webElementGuid>bd884565-86ab-40a0-89b1-77d8f4510afb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
