<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>enterMasterName</name>
   <tag></tag>
   <elementGuidId>e8d4c4b2-e5ef-493b-b8b1-7ac5434058f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text() , '${masterName}' )]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${masterName}' or . = '${masterName}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>825cd448-f562-441c-914b-e974723bbc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${masterName}</value>
      <webElementGuid>2b6d231d-ea4f-4b30-9276-4dfd7b7ae5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/a[@id=&quot;Customer Master Search&quot;]/span[1]</value>
      <webElementGuid>43e83d02-245c-4e06-9c17-40a47e61ed15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>edbe8672-dd75-45de-ac8c-ad159c8f1c53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
