<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchCurrencyBtn</name>
   <tag></tag>
   <elementGuidId>b27bb5e5-2a03-46d9-9fc7-d9f88b881ff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='refForm_curcod_searchButton']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0f3524f5-e066-4e50-a06b-865596fdcd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-search</value>
      <webElementGuid>a0f98414-c79e-48f8-b41c-3e69083045b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refForm_curcod_searchButton&quot;)/span[@class=&quot;fa fa-search&quot;]</value>
      <webElementGuid>096a66c2-ca7b-47e8-b792-87fdd28293db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='refForm_curcod_searchButton']/span</value>
      <webElementGuid>123b34d9-12b8-41e1-a1d0-2574041355a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/button/span</value>
      <webElementGuid>78e8cd72-e9e2-44d1-a583-ebcdbe6d6c62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
