<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alreadyLogin Popup-yesBtn</name>
   <tag></tag>
   <elementGuidId>06d0dab2-d6d2-47e3-8da9-e869d06e2bb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sessionConfirmAlertForm_sessionYesButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'submit' and @name = 'sessionYesButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Yes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2379220-de0f-4a29-ad21-fc6b7e4bc9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7dfd0961-c3f4-436c-aedc-e9e1f06983f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sessionYesButton</value>
      <webElementGuid>b3a5d440-f67e-4edc-96c9-608ab578f9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sessionConfirmAlertForm_sessionYesButton</value>
      <webElementGuid>c4b2cdb8-bfd7-4777-bb60-687f2b817df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>7cd4931f-f95d-4428-b15c-3378cc662430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary </value>
      <webElementGuid>9ae06763-9635-48ae-9665-5d3ce018cf84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Yes</value>
      <webElementGuid>29a43b5a-8bc3-48b9-923c-2136e92c945c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sessionConfirmAlertForm_sessionYesButton&quot;)</value>
      <webElementGuid>d23e6f76-ccf8-4ee5-9fe1-360f942936a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sessionConfirmAlertForm_sessionYesButton']</value>
      <webElementGuid>fcb817ac-c1d6-498c-a7cf-ee5f0574ff10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sessionConfirmAlertForm-form']/div[2]/div/div/button</value>
      <webElementGuid>0489dd37-3818-42e9-ac78-06c5d1873516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you want to expire the existing session and create a new one ?'])[1]/following::button[1]</value>
      <webElementGuid>ff9bdc6f-0365-4944-ad1c-5c59e5d2dcc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User already logged in.'])[1]/following::button[1]</value>
      <webElementGuid>41f753d0-8128-4366-961d-6c930c754cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>9ed2537d-2f2b-4c2f-98b7-5575dbd15443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>912cc954-e5b7-4392-9cf8-92c7ca21624d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'sessionYesButton' and @id = 'sessionConfirmAlertForm_sessionYesButton' and (text() = ' Yes' or . = ' Yes')]</value>
      <webElementGuid>f7b7b1f2-1e4a-417a-b747-4a372f337119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
